'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class learner_appeal_info

    '''<summary>
    '''txtCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourse As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAssessor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssessor As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategory As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStage As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatus As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSupportingDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupportingDoc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLearnerAppealDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLearnerAppealDescr As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtAssessorAppealDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssessorAppealDescr As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtStepsTakenAssessor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStepsTakenAssessor As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtStepsTakenManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStepsTakenManagement As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtStepsTakenExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStepsTakenExecutive As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
