'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_appeal_info

    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCourse As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModule As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAssessorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssessorName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategory As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAppealStage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAppealStage As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAppealStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAppealStatus As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLearnerAppealDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLearnerAppealDescr As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAssessorAppealDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssessorAppealDescr As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStepsTakenAssessor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStepsTakenAssessor As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStepsTakenManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStepsTakenManagement As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''stepsTakenExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stepsTakenExecutive As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBack As Global.System.Web.UI.WebControls.Button
End Class
