'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DocumentPortal

    '''<summary>
    '''lblFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFullName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liDocPortal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDocPortal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liReqPortal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liReqPortal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liNewDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liNewDoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnAllDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllDocs As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnApprovedDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApprovedDocs As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spApproved As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnPendingDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPendingDocs As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spPending As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnWithdrawnDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWithdrawnDocs As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''spWithdrawn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spWithdrawn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDocuments As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ddlReqChangeDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReqChangeDoc As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtReqChangeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReqChangeDesc As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''upReqChangeFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upReqChangeFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnSubmitRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitRequest As Global.System.Web.UI.WebControls.Button
End Class
