'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class facilitator_student_info

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''btnGoToAccDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToAccDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToAddressDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToAddressDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToNOKDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToNOKDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToEmploymentDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToEmploymentDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToSecondaryEducationDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToSecondaryEducationDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToTertiaryEducationDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToTertiaryEducationDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToWorkExperienceDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToWorkExperienceDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToComputerLiteracyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToComputerLiteracyDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnGoToLanguageProficiencyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToLanguageProficiencyDetails As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''mvRegisterLearner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvRegisterLearner As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''viewAccountDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewAccountDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCell As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTitle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtMaidenName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaidenName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRace As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMaritalStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDisability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDisability As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ddlIdentificationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdentificationType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtIdentificationValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificationValue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlEmploymentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmploymentStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''upAvatar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAvatar As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblError1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnToScreen2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewAddressDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewAddressDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostalCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''panelAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelAddress As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlArea As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblError2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnToScreen1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen1 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnToScreen3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen3 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewNOKDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewNOKDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ddlNOKTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNOKTitle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNOKFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOKFirstName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNOKMaidenName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOKMaidenName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNOKLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOKLastName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNOKRelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOKRelation As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNOKEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOKEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNOKPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOKPhone As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNOKAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOKAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Text2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''panelNOKAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelNOKAddress As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlNOKCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNOKCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlNOKRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNOKRegion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlNOKArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNOKArea As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblError3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackToScreen2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackToScreen2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnToScreen4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen4 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewSystemPermissionDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewSystemPermissionDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtEmpCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpCompanyName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmpEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmpPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpPhone As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmpAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmpPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpPostalCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''panelEmpAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelEmpAddress As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlEmpCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEmpRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpRegion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEmpArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpArea As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblError4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackToScreen3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackToScreen3 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewSecondaryEducationDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewSecondaryEducationDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtSchoolName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchoolName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlSchoolEndYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSchoolEndYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''upNSCCert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upNSCCert As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''txtSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubjectName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtMark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMark As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnAddSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSubject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvSubjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSubjects As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblError5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackToScreen4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackToScreen4 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnToScreen6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen6 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewTertiaryEducationDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewTertiaryEducationDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtInstitutionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInstitutionName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlInstitutionEndYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInstitutionEndYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''upInstitutionCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upInstitutionCertificate As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnAddQualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddQualification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvQualifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvQualifications As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button4 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewWorkExperienceDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewWorkExperienceDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''panelCriminalConviction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelCriminalConviction As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlEmploymentDismissal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmploymentDismissal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDismissalReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDismissalReason As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlCriminalConviction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCriminalConviction As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCriminalConviction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCriminalConviction As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWorkStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkStartDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWorkEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkEndDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnAddWorkExperience control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddWorkExperience As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvWorkExperience control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWorkExperience As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblError7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackToScreen6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackToScreen6 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnToScreen8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen8 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewComputerLiteracyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewComputerLiteracyDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtCompSkillName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompSkillName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlSkillRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSkillRating As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddSkill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSkill As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvSkills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSkills As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LblError8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblError8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnToScreen7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen7 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen8 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnToScreen9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToScreen9 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''viewLanguageProficiencyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewLanguageProficiencyDetails As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLanguage As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlLanguageRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLanguageRating As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddLanguage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvLanguages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLanguages As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblError9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackToscreen8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackToscreen8 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSubmitScreen9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitScreen9 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button7 As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
